### ISSUE TITLE
Selenium Standalone 5.7 does not run 

### ISSUE THREAD

**Issue by Greenbones** [vvo/selenium-standalone#225]
I've got selenium standalone installed as part of Web Component Tester and as of version 5.7 it no longer start successfully as part of a WCT run.

I get the following error:

> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> Unrecognized option: -port
> 
> Error: Selenium server did not start.Another Selenium process may already be running or your java version may be out of date.

I've reproduced this on both my build's linux docker image (java 7) and locally on my windows dev box (java 8). It didn't occur on my dev box until I reinstalled Selenium to go from 5.6.3 to 5.7.

The issue appears to be caused by commit https://github.com/vvo/selenium-standalone/commit/9f69f35a8984816ab1986dc51c8b74929358e8a6. When I run the java command the way it is constructed now, I get the same error, and when I run it the previous way, selenium starts fine.

**Comment by vvo** [comment]
@stephenash any idea? It's working for me currently but we may be missing something

**Comment by stephenash** [comment]
@Greenbones Ugh! So sorry about that. When we changed how the arguments list was build for supporting the selenium 3 betas, it broke sending selenium specific arguments (which WCT must be doing). I have a fix out for review and I made sure to add a test case so that it doesn't break again in the same way. Thanks so much for the report!

@vvo Opened up #226 with a fix
