### ISSUE TITLE
selenium standalone start failed when install single chrome driver

### ISSUE THREAD

**Issue by wck821829906** [vvo/selenium-standalone#421]
@vvo 
Steps:
1.  npm install selenium-standalone（6.15.4）
2.  install just chrome driver with "--singleDriverInstall=chrome" configuration
![image](https://user-images.githubusercontent.com/17002975/50625419-0e715c80-0f63-11e9-809f-a0525f75789e.png)
3.  start selenium standalone

Expected results:
standalone server should run successfully with single chrome driver

Actual results:
standalone server run failed, error "missing geckdriver" happens.
![image](https://user-images.githubusercontent.com/17002975/50625454-41b3eb80-0f63-11e9-8d98-586eed808ba1.png)

**Comment by mgrybyk** [comment]
Feel free to raise a fix for that!

Thanks

**Comment by christian-bromann** [comment]
@wck821829906 what would you suggest as an expected behavior here? I believe the idea of `singleDriverInstall` is to re-install a single driver. This package requires all drivers to be installed.

One solution would be to introduce a parameter called `--singleDriverStart` and only run Selenium Standalone with this single driver. What do you all think?
