### ISSUE TITLE
Getting error for selenium-standalone install command

### ISSUE THREAD

**Issue by SD-Southpaw** [vvo/selenium-standalone#439]
Hello - Im currently going through setting up a selenium environment. However when I attempt the following I am not getting the desired results; ./node_modules/.bin/selenium-standalone install
what is returned is: bash: ./node_modules/.bin/selenium-standalone: No such file or directory
Please see attached screenshot that shows my directory containing selenium-standalone and GitBash w my various attempts to get successful install. Any help is appreciated. I am new to selenium. 
![Selenium-Standalone Install](https://user-images.githubusercontent.com/51488531/59118377-cdf87f00-8904-11e9-94d6-d54f8ece217e.png)

**Comment by tzujui** [comment]
Hi
/selenium-standalone does not exist in node_modules because it was not downloaded properly. 
I am also unable to download selenium sever.jar file. 
Getting this error message `Error: Could not download https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar: Error: connect ETIMEDOUT 199.36.153.5:443`
I  tracked down and found out https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59 is inaccessible at the moment. Hope this helps!

**Comment by SD-Southpaw** [comment]
Do you mind cp the steps and version(s) you did this for???? Thanks.

**Comment by tzujui** [comment]
I did `selenium-standalone install --version=3.12.0` and get `Error: Could not download https://selenium-release.storage.googleapis.com/3.12/selenium-server-standalone-3.12.0.jar: Error: connect ETIMEDOUT 199.36.153.5:443`. This is due to `https://selenium-release.storage.googleapis.com` being inaccessible. Not sure when it will be fixed.

**Comment by SD-Southpaw** [comment]
I finally have resolved the error. It was because I did not have Java
installed. Thanks for your help.
