### ISSUE TITLE
Does Selenium-standalone use ChromeDriver by default?

### ISSUE THREAD

**Issue by Taewa** [vvo/selenium-standalone#464]
(I removed all preset of question buecase it's not a bug)

Hi all,
Sorry if it's a silly question.
I'd heard that Puppeteer is a good choice for the UI testing because it can control natively Chrome browser with ChromeDriver.

But I see ChromeDriver in selenium-standalone's folder (`selenium-standalone/.selenium/chromedriver/2.43-x64-chromedriver`).
So can I say Selenium-standalone uses ChromeDriver?

1. What I am confused is that I heard Selenium-standalone uses webDriver not ChromeDriver. But I see ChromeDriver in the `/.selenium` folder as I mentioned above.
1. If Selenium-standalone uses webDriver but testing on Chrome, would it be problem especially in headless mode?
I am facing most of issues on headless mode while non-headless mode working well. (mostly timeout or can't find an element) which led me to think if it's driver compatibility.

Any comment would be helpful.
Thanks.

## Your Environment
* Version of `selenium-standalone` that you are using: 6.16.0
* Is there another tool calling `selenium-standalone` on your behalf:
* System/platform: MacOS 10.14.6
* Other details that might be important: Using WebDriverIO5

**Comment by vvo** [comment]
> So can I say Selenium-standalone uses ChromeDriver?

Yes.

> 1. I heard Selenium-standalone uses webDriver not ChromeDriver

web driver is the protocol that allows different browsers to be controlled by selenium to do actions like "clicks" in an automated way. Since every browser has different APIs internally, they made something like a standard where evreyone speaks the same language (web driver protocol), even if their internal implementation of how to do a click is different. And ChromeDriver must be something that implements web driver protocol, as seen here: https://chromedriver.chromium.org/

![image](https://user-images.githubusercontent.com/123822/87594559-7161b900-c6ed-11ea-881b-0ed80a5946f5.png)

> 2\. If Selenium-standalone uses webDriver but testing on Chrome, would it be problem especially in headless mode?
>     I am facing most of issues on headless mode while non-headless mode working well. (mostly timeout or can't find an element) which led me to think if it's driver compatibility.

Timeouts are everywhere in browser testing indeed! I can't solve your specific problem though. But you could give a try to a different way of doing browser testing if all you need is testing ONE specific browser. For example by using https://www.cypress.io/.

https://webdriver.io/ is also a nice solution overall that could help you (this is based on selenium and webdriver).

Good luck!
