### ISSUE TITLE
install shouldnt redownload if it already exists

### ISSUE THREAD

**Issue by daleharvey** [vvo/selenium-standalone#50]

**Comment by vvo** [comment]
So that's feasible by comparing md5sums of downloaded files and keeping the original downloaded files (without uncompressing them) OR by writing down the md5sum in a file after the download is complete.

```shell
> curl -I http://chromedriver.storage.googleapis.com/2.13/chromedriver_linux64.zip 
HTTP/1.1 200 OK
Expires: Sun, 11 Jan 2015 17:40:22 GMT
Date: Sun, 11 Jan 2015 16:40:22 GMT
Last-Modified: Wed, 10 Dec 2014 13:22:58 GMT
ETag: "fcfd993330704f8cfb307a2fca5a9687"
```

The ETag is the md5sum of the file, when we download it first time we check for the md5 existence, if there's no, we download the file and write down the md5sum, next time we just compare the two

**Comment by lwhorton** [comment]
I'm confused vvo - are you planning on implementing this, or are you providing guidance so that someone might implement a server to do the etag caching?

**Comment by vvo** [comment]
I am providing a guidance on how to do it properly and will accept a PR. Also if you feel "my way" isn't the good one, implement yours, no prob and submit a PR.

Are you interested @lwhorton?

**Comment by ericelliott** [comment]
:+1:
