### ISSUE TITLE
Install could use a verbose mode

### ISSUE THREAD

**Issue by nevir** [vvo/selenium-standalone#59]
Like v2's install script; would be helpful to aid debugging, and explain to the user what's going on - as it can take a while.

**Comment by vvo** [comment]
Completely agree. In V2 there was not a clear distinction between programmatic API and command line API.

So the easiest way to do this would be to pass a log function to the programmatic API since I do not want to console.log inside the programmatic API.

The default log function should be a noop but the command line API will use console.log.

I can do this.

Thanks.

**Comment by nevir** [comment]
That sounds perfect!
