### ISSUE TITLE
Stop?

### ISSUE THREAD

**Issue by ericelliott** [vvo/selenium-standalone#66]
How do we stop selenium-standalone programatically?

**Comment by vvo** [comment]
Not obvious but https://github.com/vvo/selenium-standalone#seleniumstartopts-cb.

When starting, you get the selenium child_process and you just .kill() it when needed.

There's no magic like listening for SIGINT etc because it triggered more harm than good.

Let me know if it fits your needs and if it works @ericelliott

**Comment by ericelliott** [comment]
Thanks, I'll give this a try. If it works out, we should add it to the docs. =)

**Comment by ericelliott** [comment]
Seems to be working great. Thanks!

**Comment by vvo** [comment]
Will accept PR as for the docs :D
