### ISSUE TITLE
When crashed, the chromedriver is still running

### ISSUE THREAD

**Issue by binarykitchen** [vvo/selenium-standalone#72]
I figured out that when a fatal error occured in the middle of my tests, i.E. a TypeError, then it crashes of course. But the `ps -aux | grep selenium` command has shown that the Selenium instance is still running.

So I put this ugly hack in my Gulp:

```coffee
process.on 'exit', ->
  if seleniumProcess then seleniumProcess.kill()
```

and that solved. But there is still one process remaining: the chromedriver!

```
/node_modules/selenium-standalone/.selenium/chromedriver/2.14-x64-chromedriver --port=16277
```

How can I kill it as well? Why isn't selenium killing it?

**Comment by vvo** [comment]
That's strange indeed, this seems like a selenium issue to me.

Try to kill it with .kill('SIGKILL') or search for this selenium bug in https://code.google.com/p/selenium/issues/list

Check that you are using the latest version of selenium and chromedriver.

I wonder if we should kill the server on process.exit if server still up. What do you think?

I previously had removed this fail safe check so that users would not be confused by some magic but now that I think about it it may be better to exit.

**Comment by vvo** [comment]
I will do my own testing on this issue as well when I get some time

**Comment by binarykitchen** [comment]
Nope `.kill('SIGKILL')` didn't make any difference. Yes, I am using the latest versions of both.

**Comment by binarykitchen** [comment]
Yes, please add some tests for this. Would be good.

**Comment by vvo** [comment]
@binarykitchen please provide a runnable github project where I can reproduce the behavior. thanks

**Comment by vvo** [comment]
Cannot reproduce
