### ISSUE TITLE
How to get the Selenium logs?

### ISSUE THREAD

**Issue by Robinfr** [vvo/selenium-standalone#83]
Is there any way to have a logger that outputs all the Selenium logs when running Selenium from within Node, like the ones you see when you run the selenium-standalone server using the jar file?

The reason I'm asking is because my tests are working fine with the selenium-standalone server from Selenium, and also if I run selenium-standalone (the binary from this repo). However, if I start my tests using the selenium-standalone from within Node, halfway through it stops working and I have no idea what is going wrong since I don't seem to have any way of retrieving the logs..

**Comment by vvo** [comment]
When using the programmatic API for [start](https://github.com/vvo/selenium-standalone#seleniumstartopts-cb), you get the spawned child process in `cb(err, child)`.

What you could do then use the [child_process API](https://nodejs.org/api/child_process.html) to get the selenium logs, using stderr, stdout etc.

I am sorry it works when using the cli and fails when using the programmatic API. It's not the first time this issue shows so it would be great to finally find why.

It may be because of some $PATH or selenium detecting it's not really running in a console, I dunno.

Let me know how it goes!

**Comment by Robinfr** [comment]
Alright, so the way you get the logging from the programmatic API is by doing the following:

    child.stderr.on('data', function(data) {
        console.log(data.toString());
    });

This should probably be in the documentation as it can be quite useful. Anyway, back to the issue. When I put this piece of code in, the tests work.. So it's literally like a quantum problem, as soon as I try to observe it, the tests run fine. But when I remove this piece of code, the tests seem to stop halfway through.

Any ideas on what could be affecting this?

**Comment by vvo** [comment]
> This should probably be in the documentation as it can be quite useful.

I agree, can you do a PR to solve this?



> Anyway, back to the issue. When I put this piece of code in, the tests work.. So it's literally like a quantum problem, as soon as I try to observe it, the tests run fine. But when I remove this piece of code, the tests seem to stop halfway through.

That's a very good find, because you can reproduce it. Could you try to fix this in the library? Here's how:
- clone the project
- `npm link` into it
- go to your project using the programmatic API, do `npm link selenium-standalone`
- then you can modify the selenium-standalone project and see if you fix the issue
- I think we should just listen to stdout, stderr by default with an empty function listener ([noop](https://github.com/vvo/selenium-standalone/blob/3a532e2b54e1b262c2ed202707134811b8e5d6b2/lib/start.js#L10))

Would be so great to get your help.

**Comment by Robinfr** [comment]
I will do that when I have the time. A different way of doing it is doing:

	selenium.start({
		spawnOptions: {
			stdio: 'inherit'
		}
	}, function(err, child){})

If you do it like that, the std is shared between nodejs and the process which means you get all the output in your console like you normally would. I'm definitely not saying that should be the default, it's just another option.

After reading http://stackoverflow.com/questions/15339379/node-js-spawning-a-child-process-interactively-with-separate-stdout-and-stderr-s I have a feeling that the problem might be that the buffer never gets flushed which causes a buffer overflow in Selenium. Any idea if that could be the case?

**Comment by vvo** [comment]
> After reading http://stackoverflow.com/questions/15339379/node-js-spawning-a-child-process-interactively-with-separate-stdout-and-stderr-s I have a feeling that the problem might be that the buffer never gets flushed which causes a buffer overflow in Selenium. Any idea if that could be the case?

Yes this could completely be the case.
